name: app_japones
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.6
  provider: ^6.0.3  # Agregar esta línea para usar el paquete provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # ❌ QUITAMOS intl_utils porque ya no lo usamos

flutter:
  uses-material-design: true
  assets:
    - assets/images/flag_japan.png
    - assets/data/questions.json
  generate: true

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  preferred-supported-locales:
    - en
    - es
    - ja
